# Generated by Django 4.2.6 on 2024-02-22 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("missions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("file", models.FileField(upload_to="uploads/images/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("processed", models.BooleanField(default=False)),
                (
                    "mission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="missions.mission",
                        verbose_name="mission",
                    ),
                ),
            ],
            options={
                "db_table": "uploadedPictures",
            },
        ),
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("video_file", models.FileField(upload_to="uploads/videos/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "mission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="missions.mission",
                        verbose_name="mission",
                    ),
                ),
            ],
            options={
                "db_table": "uploadedVideos",
            },
        ),
        migrations.CreateModel(
            name="RealTime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("aircraft_lat", models.FloatField()),
                ("aircraft_lon", models.FloatField()),
                ("target_lat", models.FloatField()),
                ("target_lon", models.FloatField()),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                ("is_latest", models.BooleanField(default=True)),
                (
                    "picture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fileUpload.file",
                        verbose_name="file",
                    ),
                ),
            ],
            options={
                "db_table": "live",
            },
        ),
    ]
