# Generated by Django 4.2.6 on 2024-02-22 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fileUpload", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="file",
            old_name="file",
            new_name="picture",
        ),
    ]
