# Generated by Django 4.2.6 on 2024-02-23 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fileUpload", "0002_rename_file_file_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="realtime",
            name="picture",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="fileUpload.file",
                verbose_name="picture",
            ),
        ),
    ]
