# Generated by Django 4.2.6 on 2024-02-23 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("fileUpload", "0003_alter_realtime_picture"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="realtime",
            name="picture",
        ),
        migrations.AddField(
            model_name="realtime",
            name="file",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="fileUpload.file",
                verbose_name="file",
            ),
            preserve_default=False,
        ),
    ]
