# Generated by Django 4.2.6 on 2024-02-23 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fileUpload", "0004_remove_realtime_picture_realtime_file"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="realtime",
            table="liveMission",
        ),
    ]
