# Generated by Django 4.2.6 on 2024-02-23 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fileUpload", "0006_alter_realtime_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="realtime",
            name="is_latest",
            field=models.BooleanField(),
        ),
    ]
